#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: PSG1208
      run: |
        #cp -f rainbowthemes.tar.xz /opt/rt-n56u/trunk/user/www
        #cd /opt/rt-n56u/trunk/user/www
        #sudo chmod +x ./rainbowthemes.tar.xz
        #mkdir -p n56u_rainbow
        #tar -xvf rainbowthemes.tar.xz -C n56u_rainbow
        #sed -i "s/WEBUI_NAME=n56u_ribbon_fixed/WEBUI_NAME=n56u_rainbow/g" ./Makefile
        sed -i '$d' /opt/rt-n56u/trunk/versions.inc
        echo 'FIRMWARE_BUILDS_REV=goget' >> /opt/rt-n56u/trunk/versions.inc
        sed -i 's/20200619/goget/g' /opt/rt-n56u/trunk/versions.inc
        if [ -f shadowsocks.sh ] ; then
        cp -f shadowsocks.sh /opt/rt-n56u/trunk/user/shadowsocks/scripts/shadowsocks.sh
        echo "shadowsocks.sh copy success"
        fi
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项Shadowsocks
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config #删除配置项ssobfs
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项Dnsforwarder
        sed -i '/CONFIG_FIRMWARE_ENABLE_IPV6/d' .config #删除配置项IPV6
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config #删除配置项kms
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config #删除配置项openssh
        #sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config #删除配置项TTYD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config #删除配置项iperf3
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config #删除配置项mtr
        #sed -i '/CONFIG_FIRMWARE_WIFI2_DRIVER/d' .config #删除配置项WIFI2_DRIVER
        #sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config #删除配置项
        #sed -i '/CONFIG_FIRMWARE_INCLUDE_WYYBIN/d' .config #删除配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #删除配置项
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #科学上网插件
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=y" >> .config #simple-obfs混淆插件
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #Dnsforwarder
        echo "CONFIG_FIRMWARE_ENABLE_IPV6=y" >> .config #IPV6
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=y" >> .config #kms
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> .config #openssh
        #echo "CONFIG_FIRMWARE_INCLUDE_TTYD=y" >> .config #TTYD
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> .config #iperf3
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config #mtr
        #echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #
        #echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #
        #echo "CONFIG_FIRMWARE_WIFI2_DRIVER=3.0" >> .config #Kernel driver select for WiFi AP 2.4GHz
        echo "CONFIG_FIRMWARE_CPU_600MHZ=y" >> .config #Force MT7620 CPU clock to 600MHz
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
